#!/usr/bin/php
<?php
include_once('lib/helpers.php');
include_once('lib/clear_cache.php');
include_once('lib/Block.php');
include_once('lib/Module.php');
include_once('lib/Route.php');

// Must be ran inside a Magento project (subdirectories are okay)
if (!getRootPath()) {
  error('Mash needs to be ran inside a Magento project.');
  exit;
}

switch ($argv[1]) {
  case 'cc':
  case 'clear-cache':
    clearCache();
    break;
  case 'create-block':
    $block = new Block();
    $block->createBlock($argv[2], $argv[3]);
    break;
  case 'create-module':
    $module = new Module();
    $module->createModule($argv[2]);
    break;
  case 'create-route':
    $route = new Route();
    $route->createRoute($argv[2], $argv[3], $argv[4]);
    break;
  case 'help':
    out('clear-cache (cc)');
    out('create-block [block] [block to rewrite]');
    out('create-module [module]');
    out('create-route [module] [area] [frontname]');
    out('help');
    break;
  default:
    out('Use `mash help` for a list of commands.');
    break;
}

